# Generated by Django 2.2.6 on 2019-11-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eno', models.IntegerField()),
                ('esal', models.FloatField()),
                ('eaddress', models.CharField(max_length=40)),
            ],
        ),
    ]
